steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/rutvik100886648/my-image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/rutvik100886648/my-image:$COMMIT_SHA']
options:
  defaultLogsBucket: 'gs://your-build-logs-bucket'
